### ISSUE TITLE
【Question】How can build The io.github.landrynorris:ffmpegkit

### ISSUE THREAD

**Issue by JackyYangPassion** [LandryNorris/FFmpegKitKotlinTestApp#1]
When I Build This APP  
Error log
  
 > Could not find io.github.landrynorris:ffmpegkit:0.0.21.

But when I build this Project Failed on my env
-- pod version  1.15.2

RUN  CMD
```
 ./gradlew build
```

Error log
```
FFmpegKitKotlin/ffmpegkit/src/iosMain/kotlin/com/example/ffmpegkit/ArchDetect.kt:4:28 Unresolved reference: cocoapods

```

**Comment by LandryNorris** [comment]
The library lives in a different repo [here](https://github.com/LandryNorris/FFmpegKitKotlin). I never published it, so you'll have to pull it and publish to maven local.

**Comment by LandryNorris** [comment]
The FFmpegKit wrappers for KMM ought to be pretty complete (at least for the version of FFmpegKit it's based on). I never really finished the test app.

**Comment by JackyYangPassion** [comment]
I got it,
thanks for your reply
